theme: 
  dark: dark-catppuccin
  light: light-catppuccin
symbolPreset: nerd
colorBlindMode: false
statusLine: 
  separator: powerline-thin
display: 
  showTokenUsage: true
  shimmer: classic
clearOnShrink: true
hideThinkingBlock: true
autoResume: true
steeringMode: one-at-a-time
treeFilterMode: default
startup: 
  checkUpdate: false
collapseChangelog: true
edit: 
  mode: hashline
memory: 
  backend: mnemopi
todo: 
  eager: true
calc: 
  enabled: true
renderMermaid: 
  enabled: true
inspect_image: 
  enabled: true
github: 
  enabled: true
dev: 
  autoqa: true
secrets: 
  enabled: true
disabledProviders: 
  - claude
  - claude-plugins
branchSummary: 
  enabled: true
commands: 
  enableClaudeUser: false
  enableClaudeProject: false
  enableOpencodeUser: false
  enableOpencodeProject: false
skills: 
  enableSkillCommands: true
modelRoles: 
  default: deepseek/deepseek-v4-flash
  smol: deepseek/deepseek-v4-flash:off
  commit: deepseek/deepseek-v4-flash:off
  task: deepseek/deepseek-v4-flash:off
  slow: deepseek/deepseek-v4-pro:xhigh
  plan: deepseek/deepseek-v4-pro
  designer: deepseek/deepseek-v4-pro
lsp: 
  formatOnWrite: true
  diagnosticsOnEdit: true
read: 
  toolResultPreview: false
  summarize: 
    enabled: true
compaction: 
  handoffSaveToDisk: true
python: 
  kernelMode: session
task: 
  isolation: 
    mode: auto
contextPromotion: 
  enabled: false
lastChangelogVersion: 15.5.2
setupVersion: 1
defaultThinkingLevel: auto
mnemopi: 
  scoping: per-project-tagged
  autoRecall: true
ttsr: 
  repeatMode: once
  contextMode: discard