promptToReturnFromSubprocess: false
git:
  pagers:
    - {}
    - externalDiffCommand: 'pwsh.exe -NoProfile -File "C:\Users\ASUS1\AppData\Local\lazygit\lazygit-pager.ps1"'

gui:
  language: "en"
  nerdFontsVersion: "3"
  splitDiff: "auto"

notARepository: quit
os:
  editPreset: "nvim"
